### ISSUE TITLE
Monolith build 125 fails to load 

### ISSUE THREAD

**Issue by addstar** [AddstarMC/Monolith#5]
It looks like the change https://github.com/AddstarMC/Monolith/commit/6dc736880b3c2dfe7db917fbb33200c0b1ad33ec seems to have introduced this error:

Build 125 fails to enable.

```
[18:54:44] [Server thread/INFO]: [Monolith] Enabling Monolith v1.6.0-SNAPSHOT-
[18:54:44] [Server thread/INFO]: [Monolith] Your server is running version v1_14_R1
[18:54:44] [Server thread/INFO]: [Monolith] au.com.addstar.monolith.internal.lookup.ItemDB added 6402 search items
[18:54:44] [Server thread/INFO]: [Monolith] au.com.addstar.monolith.internal.lookup.EnchantDB added 100 search items
[18:54:44] [Server thread/INFO]: [Monolith] au.com.addstar.monolith.internal.lookup.PotionsDB added 83 search items
[18:54:44] [Server thread/ERROR]: Error occurred while enabling Monolith v1.6.0-SNAPSHOT- (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant org.bukkit.entity.EntityType.WEATHER
        at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_191]
        at org.bukkit.entity.EntityType.valueOf(EntityType.java:23) ~[patched_1.14.2.jar:git-Paper-55]
        at au.com.addstar.monolith.internal.lookup.EntityDB.getObject(EntityDB.java:41) ~[?:?]
        at au.com.addstar.monolith.internal.lookup.EntityDB.getObject(EntityDB.java:18) ~[?:?]
        at au.com.addstar.monolith.internal.lookup.FlatDb.load(FlatDb.java:51) ~[?:?]
        at au.com.addstar.monolith.lookup.Lookup.initialize(Lookup.java:97) ~[?:?]
        at au.com.addstar.monolith.Monolith.onEnable(Monolith.java:46) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.2.jar:git-Paper-55]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.2.jar:git-Paper-55]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419) ~[patched_1.14.2.jar:git-Paper-55]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464) ~[patched_1.14.2.jar:git-Paper-55]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378) ~[patched_1.14.2.jar:git-Paper-55]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464) ~[patched_1.14.2.jar:git-Paper-55]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.14.2.jar:git-Paper-55]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:855) ~[patched_1.14.2.jar:git-Paper-55]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[18:54:44] [Server thread/INFO]: [Monolith] Disabling Monolith v1.6.0-SNAPSHOT-
```

Build 124 loads properly:
```
[19:11:27] [Server thread/INFO]: [Monolith] Enabling Monolith v1.6.0-SNAPSHOT-
[19:11:27] [Server thread/INFO]: [Monolith] Your server is running version v1_14_R1
[19:11:27] [Server thread/ERROR]: [Monolith] This plugin is for NMS Version 1.12.R1 or Server Version 1.12 Disabled
```

**Comment by addstar** [comment]
Additionally, after the fix in dca449642a550765d633bc7b17d423963b57ce03 Monolith now loads but has these errors:
```
[21:54:57 INFO]: [Monolith] Enabling Monolith v1.6.0-SNAPSHOT-
[21:54:57 INFO]: [Monolith] Your server is running version v1_14_R1
[21:54:57 INFO]: [RCON] /10.7.0.1:47482 Disconnected: Server is starting up
[21:54:57 INFO]: [Monolith] au.com.addstar.monolith.internal.lookup.ItemDB added 6402 search items
[21:54:57 INFO]: [Monolith] au.com.addstar.monolith.internal.lookup.EnchantDB added 100 search items
[21:54:57 INFO]: [Monolith] au.com.addstar.monolith.internal.lookup.PotionsDB added 83 search items
[21:54:57 WARN]: [au.com.addstar.monolith.internal.lookup.EntityDB] LINGERING_POTION cannot be parsed to an entity
[21:54:57 WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.entity.EntityType.LINGERING_POTION
[21:54:57 WARN]:        at java.lang.Enum.valueOf(Enum.java:238)
[21:54:57 WARN]:        at org.bukkit.entity.EntityType.valueOf(EntityType.java:23)
[21:54:57 WARN]:        at au.com.addstar.monolith.internal.lookup.EntityDB.getObject(EntityDB.java:38)
[21:54:57 WARN]:        at au.com.addstar.monolith.internal.lookup.EntityDB.getObject(EntityDB.java:14)
[21:54:57 WARN]:        at au.com.addstar.monolith.internal.lookup.FlatDb.load(FlatDb.java:51)
[21:54:57 WARN]:        at au.com.addstar.monolith.lookup.Lookup.initialize(Lookup.java:97)
[21:54:57 WARN]:        at au.com.addstar.monolith.Monolith.onEnable(Monolith.java:46)
[21:54:57 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[21:54:57 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[21:54:57 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419)
[21:54:57 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464)
[21:54:57 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378)
[21:54:57 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464)
[21:54:57 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280)
[21:54:57 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:855)
[21:54:57 WARN]:        at java.lang.Thread.run(Thread.java:748)
[21:54:57 WARN]: [au.com.addstar.monolith.internal.lookup.EntityDB]  PANDA cannot be parsed to an entity
[21:54:57 WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.entity.EntityType. PANDA
[21:54:57 WARN]:        at java.lang.Enum.valueOf(Enum.java:238)
[21:54:57 WARN]:        at org.bukkit.entity.EntityType.valueOf(EntityType.java:23)
[21:54:57 WARN]:        at au.com.addstar.monolith.internal.lookup.EntityDB.getObject(EntityDB.java:38)
[21:54:57 WARN]:        at au.com.addstar.monolith.internal.lookup.EntityDB.getObject(EntityDB.java:14)
[21:54:57 WARN]:        at au.com.addstar.monolith.internal.lookup.FlatDb.load(FlatDb.java:51)
[21:54:57 WARN]:        at au.com.addstar.monolith.lookup.Lookup.initialize(Lookup.java:97)
[21:54:57 WARN]:        at au.com.addstar.monolith.Monolith.onEnable(Monolith.java:46)
[21:54:57 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[21:54:57 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[21:54:57 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419)
[21:54:57 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464)
[21:54:57 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378)
[21:54:57 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464)
[21:54:57 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280)
[21:54:57 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:855)
[21:54:57 WARN]:        at java.lang.Thread.run(Thread.java:748)
[21:54:57 WARN]: [au.com.addstar.monolith.internal.lookup.EntityDB]  RAVAGER cannot be parsed to an entity
[21:54:57 WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.entity.EntityType. RAVAGER
[21:54:57 WARN]:        at java.lang.Enum.valueOf(Enum.java:238)
[21:54:57 WARN]:        at org.bukkit.entity.EntityType.valueOf(EntityType.java:23)
[21:54:57 WARN]:        at au.com.addstar.monolith.internal.lookup.EntityDB.getObject(EntityDB.java:38)
[21:54:57 WARN]:        at au.com.addstar.monolith.internal.lookup.EntityDB.getObject(EntityDB.java:14)
[21:54:57 WARN]:        at au.com.addstar.monolith.internal.lookup.FlatDb.load(FlatDb.java:51)
[21:54:57 WARN]:        at au.com.addstar.monolith.lookup.Lookup.initialize(Lookup.java:97)
[21:54:57 WARN]:        at au.com.addstar.monolith.Monolith.onEnable(Monolith.java:46)
[21:54:57 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[21:54:57 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[21:54:57 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419)
[21:54:57 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464)
[21:54:57 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378)
[21:54:57 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464)
[21:54:57 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280)
[21:54:57 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:855)
[21:54:57 WARN]:        at java.lang.Thread.run(Thread.java:748)
[21:54:57 WARN]: [au.com.addstar.monolith.internal.lookup.EntityDB]  RAVAGER cannot be parsed to an entity
[21:54:57 WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.entity.EntityType. RAVAGER
[21:54:57 WARN]:        at java.lang.Enum.valueOf(Enum.java:238)
[21:54:57 WARN]:        at org.bukkit.entity.EntityType.valueOf(EntityType.java:23)
[21:54:57 WARN]:        at au.com.addstar.monolith.internal.lookup.EntityDB.getObject(EntityDB.java:38)
[21:54:57 WARN]:        at au.com.addstar.monolith.internal.lookup.EntityDB.getObject(EntityDB.java:14)
[21:54:57 WARN]:        at au.com.addstar.monolith.internal.lookup.FlatDb.load(FlatDb.java:51)
[21:54:57 WARN]:        at au.com.addstar.monolith.lookup.Lookup.initialize(Lookup.java:97)
[21:54:57 WARN]:        at au.com.addstar.monolith.Monolith.onEnable(Monolith.java:46)
[21:54:57 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[21:54:57 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[21:54:57 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419)
[21:54:57 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464)
[21:54:57 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378)
[21:54:57 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464)
[21:54:57 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280)
[21:54:57 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:855)
[21:54:57 WARN]:        at java.lang.Thread.run(Thread.java:748)
[21:54:57 WARN]: [au.com.addstar.monolith.internal.lookup.EntityDB]  PILLAGER cannot be parsed to an entity
[21:54:57 WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.entity.EntityType. PILLAGER
[21:54:57 WARN]:        at java.lang.Enum.valueOf(Enum.java:238)
[21:54:57 WARN]:        at org.bukkit.entity.EntityType.valueOf(EntityType.java:23)
[21:54:57 WARN]:        at au.com.addstar.monolith.internal.lookup.EntityDB.getObject(EntityDB.java:38)
[21:54:57 WARN]:        at au.com.addstar.monolith.internal.lookup.EntityDB.getObject(EntityDB.java:14)
[21:54:57 WARN]:        at au.com.addstar.monolith.internal.lookup.FlatDb.load(FlatDb.java:51)
[21:54:57 WARN]:        at au.com.addstar.monolith.lookup.Lookup.initialize(Lookup.java:97)
[21:54:57 WARN]:        at au.com.addstar.monolith.Monolith.onEnable(Monolith.java:46)
[21:54:57 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[21:54:57 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[21:54:57 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419)
[21:54:57 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464)
[21:54:57 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378)
[21:54:57 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464)
[21:54:57 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280)
[21:54:57 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:855)
[21:54:57 WARN]:        at java.lang.Thread.run(Thread.java:748)
[21:54:57 WARN]: [au.com.addstar.monolith.internal.lookup.EntityDB]  TRADER_LLAMA cannot be parsed to an entity
[21:54:57 WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.entity.EntityType. TRADER_LLAMA
[21:54:57 WARN]:        at java.lang.Enum.valueOf(Enum.java:238)
[21:54:57 WARN]:        at org.bukkit.entity.EntityType.valueOf(EntityType.java:23)
[21:54:57 WARN]:        at au.com.addstar.monolith.internal.lookup.EntityDB.getObject(EntityDB.java:38)
[21:54:57 WARN]:        at au.com.addstar.monolith.internal.lookup.EntityDB.getObject(EntityDB.java:14)
[21:54:57 WARN]:        at au.com.addstar.monolith.internal.lookup.FlatDb.load(FlatDb.java:51)
[21:54:57 WARN]:        at au.com.addstar.monolith.lookup.Lookup.initialize(Lookup.java:97)
[21:54:57 WARN]:        at au.com.addstar.monolith.Monolith.onEnable(Monolith.java:46)
[21:54:57 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[21:54:57 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[21:54:57 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419)
[21:54:57 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464)
[21:54:57 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378)
[21:54:57 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464)
[21:54:57 WARN]: [au.com.addstar.monolith.internal.lookup.EntityDB]  WANDERING_TRADER cannot be parsed to an entity
[21:54:57 WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.entity.EntityType. WANDERING_TRADER
[21:54:57 WARN]:        at java.lang.Enum.valueOf(Enum.java:238)
[21:54:57 WARN]:        at org.bukkit.entity.EntityType.valueOf(EntityType.java:23)
[21:54:57 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[21:54:57 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419)
[21:54:57 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464)
[21:54:57 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378)
[21:54:57 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464)
[21:54:57 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280)
[21:54:57 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:855)
[21:54:57 WARN]:        at java.lang.Thread.run(Thread.java:748)
[21:54:57 WARN]: [au.com.addstar.monolith.internal.lookup.EntityDB]  FOX cannot be parsed to an entity
[21:54:57 WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.entity.EntityType. FOX
[21:54:57 WARN]:        at java.lang.Enum.valueOf(Enum.java:238)
[21:54:57 WARN]:        at org.bukkit.entity.EntityType.valueOf(EntityType.java:23)
[21:54:57 WARN]:        at au.com.addstar.monolith.internal.lookup.EntityDB.getObject(EntityDB.java:38)
[21:54:57 WARN]:        at au.com.addstar.monolith.internal.lookup.EntityDB.getObject(EntityDB.java:14)
[21:54:57 WARN]:        at au.com.addstar.monolith.internal.lookup.FlatDb.load(FlatDb.java:51)
[21:54:57 WARN]:        at au.com.addstar.monolith.lookup.Lookup.initialize(Lookup.java:97)
[21:54:57 WARN]:        at au.com.addstar.monolith.Monolith.onEnable(Monolith.java:46)
[21:54:57 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[21:54:57 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[21:54:57 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419)
[21:54:57 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464)
[21:54:57 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378)
[21:54:57 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464)
[21:54:57 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280)
[21:54:57 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:855)
[21:54:57 WARN]:        at java.lang.Thread.run(Thread.java:748)
[21:54:57 INFO]: [Monolith] au.com.addstar.monolith.internal.lookup.EntityDB added 140 search items
```
